server:
  port: 80

# public key for datasource password
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ8GS6CxvZuqrocKE+84hO0dia8rvOOBVGvQgzFLeexcocfzUFSgiT7qFZQashlto/QDQLV3p94B0Nti9MUtV98CAwEAAQ==

spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mmall?characterEncoding=utf-8&useSSL=false
    username: root
    password: hMwrf1tcv5vRpcmiBwXx1T70OLE4oAEHPWQA9DQeO+UQSmNNmJl4rPua2eVVOH7AR8286xvC/A4RVZi9FVITTQ==
    druid:
      initial-size: 5
      max-active: 10
      filters: stat,wall
      stat-view-servlet:
        login-username: admin
        login-password: pa4word
        reset-enable: false
      aop-patterns: cn.waynechu.mmall.service.*
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true
  # redis sentinel
  redis:
      host: 127.0.0.1
      port: 6379
      password:
      sentinel:
        master: mymaster
        nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
  # multipart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# mybatis
mybatis:
    type-aliases-package: cn.waynechu.mmall.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
          cache-enabled: false
          map-underscore-to-camel-case: true
          use-generated-keys: true
# mybatis pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# ftp
ftp:
  server:
    ip: 206.189.41.1
    url-prefix: http://img.topblog.top/
    user: ftpuser
    password: lookatmenow