spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/mmall?characterEncoding=utf-8&useSSL=false
    username: root
    password: EwNz3/EWvXIHhJsLq+Q8jHwqA7LJBBmYRJ3D4KRnuNDjfTWX0Rrsm3Im11Ll+WYd92qacPEUXNnFYUAhiNeKng==
    druid:
      initial-size: 5
      max-active: 10
      filters: stat,wall
      stat-view-servlet:
        login-username: admin
        login-password: pa4word
        reset-enable: false
      aop-patterns: cn.waynechu.mmall.service.*
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true

  # redis
  redis:
    host: 192.168.1.100
    port: 6379
    password: 123456

server:
  port: 80

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIIzAa+DzYwsgscjjyKvwlrjKguFMU/WGxt9ezWoHwuiwac/tVbHjjAK4J/RfoyxyS6t7oDctcGIyTGj4DGdS/UCAwEAAQ==


ftp:
  server:
    ip: 192.168.1.100
    url-prefix: http://www.topblog.cn
    username: waynechu
    password: pa4word