spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmall?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 5
      max-active: 10
      filters: stat,wall
      aop-patterns: cn.waynechu.mmall.service.*

  # redis
  redis:
    host: localhost
    port: 6379
    password: 123456

server:
  port: 8080