server:
  port: 80

# public key for datasource password
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIIzAa+DzYwsgscjjyKvwlrjKguFMU/WGxt9ezWoHwuiwac/tVbHjjAK4J/RfoyxyS6t7oDctcGIyTGj4DGdS/UCAwEAAQ==

spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/mmall?characterEncoding=utf-8&useSSL=false
    username: root
    password: EwNz3/EWvXIHhJsLq+Q8jHwqA7LJBBmYRJ3D4KRnuNDjfTWX0Rrsm3Im11Ll+WYd92qacPEUXNnFYUAhiNeKng==
    druid:
      initial-size: 5
      max-active: 10
      filters: stat,wall
      stat-view-servlet:
        login-username: admin
        login-password: pa4word
        reset-enable: false
      aop-patterns: cn.waynechu.mmall.service.*
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true
  # redis sentinel
  redis:
      host: 192.168.1.107
      port: 6379
      password: pa4word
      sentinel:
        master: mymaster
        nodes: 192.168.1.107:26379,192.168.1.107:26380,192.168.1.107:26381
  # multipart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
    type-aliases-package: cn.waynechu.mmall.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
          cache-enabled: false
          map-underscore-to-camel-case: true
          use-generated-keys: true

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

ftp:
  server:
    ip: 206.189.41.1
    url-prefix: http://img.topblog.top/
    user: ftpuser
    password: lookatmenow