server:
  port: 8080

spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmall?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 5
      max-active: 10
      filters: stat,wall
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: true
      aop-patterns: cn.waynechu.mmall.service.*
  # redis sentinel
  redis:
    host: localhost
    port: 6379
    password:
    sentinel:
      master: mymaster
      nodes: localhost:26379,localhost:26380,localhost:26381
  # multipart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
    type-aliases-package: cn.waynechu.mmall.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
          cache-enabled: false
          map-underscore-to-camel-case: true
          use-generated-keys: true
          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

ftp:
  server:
    ip: 192.168.1.107
    url-prefix: http://192.168.1.107:10080/
    user: ftpuser
    password: 123456