server:
  port: 80

# public key for datasource password
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK3/Tq6zX0MjlMGkWFkdL3tZaZTY+5sAJO/BOYDSO/kVYeUSIRBADN0RIOjn2Nldfj8/ThjhPPVZoBQ3jC8+BtcCAwEAAQ==

spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://206.81.7.89:3306/mmall?characterEncoding=utf-8&useSSL=false
    username: root
    password: PQU7xpcGph9BAJ7vhCIOJMbT5K1a3X6aUEpjUtQcJetAOlwh7JEX2fXyaIxEwCe8O4t57JtbbqG81gR4xS8Tew==
    druid:
      initial-size: 5
      max-active: 10
      filters: stat,wall
      stat-view-servlet:
        login-username: admin
        login-password: pa4word
        reset-enable: false
      aop-patterns: cn.waynechu.mmall.service.*
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true
  # redis sentinel
  redis:
      host: 127.0.0.1
      port: 6379
      password:
      sentinel:
        master: mymaster
        nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
  # multipart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# mybatis
mybatis:
    type-aliases-package: cn.waynechu.mmall.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
          cache-enabled: false
          map-underscore-to-camel-case: true
          use-generated-keys: true
# mybatis pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# ftp
ftp:
  server:
    ip: 206.189.41.1
    url-prefix: http://img.topblog.top/
    user: ftpuser
    password: lookatmenow